services:
  - type: web
    name: smart-farming
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGO_URI
        sync: false
      - key: DATABASE_NAME
        sync: false
    healthCheckPath: /
